# Generated by Django 3.2.9 on 2021-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
